theme: jekyll-theme-dinky

title: <a href='/react-iga/2019'>React IGA</a>
description: [<p>Technologies Web synchrones et multi-dispositifs</p><ul><li><a href='/react-iga/2019/#plan-du-cours'>Cours</a></li><li><a href='/react-iga/2019/#tp'>TP</a></li><li><a href='/react-iga/2019/#evaluation'>Evaluation</a></li></ul>]
